### ISSUE TITLE
Browser tab not working with proxy

### ISSUE THREAD

**Issue by crissi** [itsgoingd/clockwork#138]
I am sending ajax request though a proxy before reaching my API.

The storage/clockwork files are created as expected, but nothing ever shows up in the chrome clockwork tab.

Response headers are populated with:
```
x-clockwork-id:1466974245.7710.276943226
x-clockwork-version:1.12
x-powered-by:PHP/7.0.0
```
If I take the header value x-clockwork-id from the request and try it with the route:
`<url>i/__clockwork/{header_id}`
 for both the proxy url and api url they both return the data as expected.

**Comment by itsgoingd** [comment]
Hey, can you describe your setup in more detail, or even better send me some config files and steps to reproduce?

The proxy shouldn't cause any issues to Clockwork as long as it's transparent and doesn't modify the headers. The metadata retrieval on the extension part is done via a simple ajax request based on the header value.

**Comment by crissi** [comment]
I have debugged a bit.

My proxy is http://localhost:8100/api and relays to http://app.dev.

The problem is clockworks calls this url:
http://localhost:8100/__clockwork/1467545512.0709.847527557.

without the /api part, so it is not hitting my server.

The extension error is this:
Failed to load resource: the server responded with a status of 404 (Not Found)
background.js:12 Error getting Clockwork metadata:
background.js:13 Cannot GET /__clockwork/1467545543.8631.1443573305

Is there anyway to tell to the clockwork to include /api in the url.

**Comment by itsgoingd** [comment]
Yeah, that's the problem, Clockwork normally auto-detects if the app is running in a subdirectory, but since your app itself is running in the document root, it has no way to know it should append the "/app" prefix to the metadata calls.

The metadata path is sent to the extension via a header, you should be able to easily fix the problem by sending a `X-Clockwork-Path` header with the value `/app/__clockwork/` in your app responses.

**Comment by crissi** [comment]
:thumbsup:
