### ISSUE TITLE
Log files are huge. 

### ISSUE THREAD

**Issue by nivv** [itsgoingd/clockwork#140]
Hi! 

Thanks for a great package! I've use it for all my PHP-projects. The problem, sometimes I forget to put the app in production mode. Instead it sits in debug mode, which then makes Clockwork to log files in the storage dir (which it should). 

Problem is that it will slowly but steadily eat up your disk space. Would be nice to see a max file size or a logrotate implemented.

I know this is my fault, setting the app in debug mode. I've been caught out more than once. Just a heads up.

**Comment by itsgoingd** [comment]
Hey, there is actually a `clockwork:clean` command since forever, it's just not documented anywhere I guess, oops. You can throw it into Laravel scheduler and keep only the last X days of Clockwork data or something like that.

Also I'd suggest trying out the SQL metadata storage, it's much more manageable than a bunch of json files and deleting old data is as simple as running a delete query. Unfortunately this won't yet work with `clockwork:clean`, I'll take a look at that for the next release.

Thanks!

**Comment by nivv** [comment]
@itsgoingd oh! thanks! :) I'll look into the  `clean` command and the SQL thing.

**Comment by robclancy** [comment]
It really needs to delete old logs. You will get this exact issue come up over and over again. I just got rid of over 20 gigs and the last time I cleared the logs wasn't even long ago.

**Comment by itsgoingd** [comment]
Yeah, you can always schedule the clean command, but I'll take a look into adding automated removal of the old data in the next release.

**Comment by robclancy** [comment]
I have once again run into this issue. Caused vscode to use 1.1gigs because it was watching those files, probably get the same issue in other editors/ides when not excluded.

Libraries and extensions need to be responsible for what they do to your computer or server and shouldn't need their own undocumented maintenance tasks.

**Comment by itsgoingd** [comment]
Hey, the auto-cleanup feature is still coming, as a temporary workaround I suggest using the "sql" storage option, which will at least contain all the data in a single sqlite database.

One of the reasons why this is taking so long is a planned complete storage system overhaul to make some future features possible and switching the default storage option to "sql". This is a big breaking change, since the library will now require sqlite in the default configuration, which means I need to release a new major version for the first time.

There will be one last 1.x version with some remaining bug fixes, then I'll turn my attention to 2.0. I hate to promise any time frames, but I will try to get this done by the end of the month or June at the latest.

> Libraries and extensions need to be responsible for what they do to your computer or server and shouldn't need their own undocumented maintenance tasks.

I absolutely agree, there is still a lot that can (and will) be improved, both in the code and with documentation.

**Comment by itsgoingd** [comment]
Auto-cleanup is now a thing as of Clockwork 2.0. 🚀

**Comment by bertheyman** [comment]
For people researching the log files size and ending up here:

Auto-cleanup is enabled **by default** but has a chance to run of 1% every request. (don't assume it's not working too soon) If needed, use the `php artisan clockwork:clean` command or check the auto-cleanup after quite a few requests.
