### ISSUE TITLE
Lumen 5.4 : empty databaseQueries when using Illuminate\Support\Facades\DB

### ISSUE THREAD

**Issue by jakedowns** [itsgoingd/clockwork#174]
Hello, first let me say thank you for a superb tool I've been using with Laravel for YEARS!
You've saved me countless hours of tracking down perf. issues.

Anyway, I'm playing around with Lumen 5.4 and I just noticed that I don't seem to get any Database Query times like I'm expecting.

I'm not using Eloquent at the moment, only Query Builder.

Is there something special I need to do to enable this?

Thanks again!

**Comment by itsgoingd** [comment]
Hey, thanks for the kind words!

Currently you'll have to call `$app->withEloquent()` in your bootstrap file for Clockwork to start logging queries even when you don't use Eloquent. This doesn't affect performance at all if most of your app requests execute db queries. The only difference is that `withEloquent` resolves the db connection immediately, otherwise the connection is resolved on the first query.

I'll probably remove the existing connection check in the next version of Clockwork so it works even without that option.

**Comment by jakedowns** [comment]
Ah, perfect. Might be good to add a line about that to the Lumen section of the Readme in the meantime, but that worked perfectly. I'll go ahead and close this. ^_^

**Comment by itsgoingd** [comment]
Added note about this to the readme as this behavior won't change for now.
