### ISSUE TITLE
URL with dots (.) fails in Lumen, info is not showing in Chrome plugin

### ISSUE THREAD

**Issue by Tibbelit** [itsgoingd/clockwork#198]
Hi!

I'm having problem getting Clockwork to work with Lumen 5.5. The problem is that the URL `http://localhost:8000/__clockwork/1506542746.9891.787602072` is generating a 404 error because of the dots in the URL (I think). If I filename for the log (without dots) and then access it by `http://localhost:8000/__clockwork/15065427469891787602072` i get the log.

I guess this is why the plugin in Chrome doesn't show any request data.

I'm using PHP 7.1.1 and the build in web server by `php -S localhost:8000`

Is there a fix for this? Thanks!

Edit: Is it related to the [build in web server](https://bugs.php.net/bug.php?id=61286), is it possible to change the filename/id to exclude dots?

**Comment by itsgoingd** [comment]
Hey,

I’ve run into the same issue a few days ago while working on the Slim integration, thought it was a Slim issue at first, but suspected it might be the php server. Thanks for the bug report link confirming this.

We could change the dots to dashes for example. 

I don’t really like changing code to fix problems with 3rd party software, but since it’s such a common web server I’ll consider it.

I’m releasing 2.0 this week, so it’s a pretty good time to make the change.. let me think about it. :)

**Comment by Tibbelit** [comment]
I can confirm that it's workning now, thanks! =)
- Lumen 5.5
- PHP 7.1.1
- Clockwork 2.0.1
with PHP build in web server
