### ISSUE TITLE
Enable flag is not adhered

### ISSUE THREAD

**Issue by dionysiosarvanitis** [itsgoingd/clockwork#202]
`ClockworkMiddleware` gets called despite setting `'enable' => false`

As stated in [documentation](https://laravel.com/docs/5.5/providers#writing-service-providers): 
>Within the register method, you should only bind things into the service container. You should never attempt to register any event listeners, routes, or any other piece of functionality within the register method.

Moving the following calls to the Service Provider's boot() method (after `isEnabled` check) instead of the register() method fixed the issue.

```php
$this->registerCommands();
$this->registerMiddleware();
```

**Comment by itsgoingd** [comment]
Hey, it does indeed get registered, but doesn't really do anything, since we [check if Clockwork is enabled](https://github.com/itsgoingd/clockwork/blob/master/Clockwork/Support/Laravel/ClockworkSupport.php#L103-L105) again in the middleware.

Unfortunately Laravel 4.2 requires the middleware to be registered before boot method is run, so I've decided to register middlewares for all versions this way.

**Comment by itsgoingd** [comment]
As of Clockwork 3.0, the middleware is now registered in the boot method - [blog post](https://underground.works/blog/clockwork-3.0-now-available) and [full changelog](https://underground.works/clockwork/changelog#content).
