### ISSUE TITLE
Webview is not showing angular data and styles

### ISSUE THREAD

**Issue by uonick** [itsgoingd/clockwork#238]
Fresh install on many laravel projects. Project in Vagrant (VirtualBox/Ubuntu) machine. 

* [Laravel 5.6](https://github.com/laravel/laravel)
* [Vagrant machine](https://github.com/uonick/laravel-vm)
* Vendor published

route `__clockwork/` looks like:

<img width="944" alt="screen shot 2018-02-27 at 23 33 09" src="https://user-images.githubusercontent.com/365029/36747513-07c93cd0-1c17-11e8-98f4-242862591067.png">
<img width="896" alt="screen shot 2018-02-27 at 23 33 37" src="https://user-images.githubusercontent.com/365029/36747514-07f7ec06-1c17-11e8-9f8c-5fe0aacd1ea4.png">
<img width="912" alt="screen shot 2018-02-27 at 23 33 53" src="https://user-images.githubusercontent.com/365029/36747517-0817b504-1c17-11e8-84af-77a9786e7ff4.png">
<img width="1238" alt="screen shot 2018-02-27 at 23 34 08" src="https://user-images.githubusercontent.com/365029/36747518-083c3ece-1c17-11e8-8272-aabe8a743477.png">
<img width="1288" alt="screen shot 2018-02-27 at 23 34 32" src="https://user-images.githubusercontent.com/365029/36747519-0861f556-1c17-11e8-8826-0c22ee4598b0.png">

what could be the problem?

**Comment by itsgoingd** [comment]
Hey, I believe this is a problem with your nginx configuration,

the location block matching requests for css and js files - https://github.com/uonick/laravel-vm/blob/master/scripts/post-nginx.sh#L54-L57 - is missing the `try_files` statement, so these requests never reach php, which is necessary in this case since we are using Laravel controller for serving the assets.

**Comment by uonick** [comment]
Thank you! That helped!
