### ISSUE TITLE
Detecting Laravel middleware on routes

### ISSUE THREAD

**Issue by Vercoutere** [itsgoingd/clockwork#239]
I've been searching around for a bit but can't find any concrete information about this, so I'm not sure if this is an actual supported feature. My apologies if it isn't.

In the routes tab there are `before` and `after` columns.

<img width="635" alt="screenshot 2018-02-28 23 43 01" src="https://user-images.githubusercontent.com/3820377/36817357-2a3174fc-1ce1-11e8-8b1a-feed0dd19ef2.png">

I was under the impression these are intended to show middleware that are registered for the route in question, however I can't seem to get Clockwork to display anything there.

I've tried registering middleware globally, on the route by chaining the `middleware` method, and in controllers.

Am I misinterpreting the intention of these columns, or do I need to take any special measures to make sure middleware get picked up by Clockwork?

**Comment by itsgoingd** [comment]
Hey, these are before/after filters from Laravel 4 times, looks like we never added support for route middleware. I will take a look at it.

**Comment by Vercoutere** [comment]
Ooooh, right! I totally forgot about those.

Let me know if you want any help with this. It's a feature I'd very much appreciate, so I might as well put in some time to try and assist.

**Comment by itsgoingd** [comment]
If you'd like to have a go at implementing this I'll gladly accept a PR.

All we need to do is add collecting of the middleware on the server-side here using your code snippet - https://github.com/itsgoingd/clockwork/blob/master/Clockwork/DataSource/LaravelDataSource.php#L203-L208

(I would prefer storing it as an array though, instead of imploding to string as we do with the before/after filters.)

Duplicate the same handling as before/after filters in the extension, PR for this should be sent to the [clockwork-chrome](https://github.com/itsgoingd/clockwork-chrome) repo.

**Comment by Vercoutere** [comment]
See #240 and https://github.com/itsgoingd/clockwork-chrome/pull/44

**Comment by itsgoingd** [comment]
Released in 2.2, thanks for your PR!
