### ISSUE TITLE
Laravel 5.5 undefined offset: 0 on EloquentDatasource

### ISSUE THREAD

**Issue by Fagl4** [itsgoingd/clockwork#246]
Does not work with  https://github.com/GeneaLabs/laravel-model-caching  installed and trait applied to models, crashes with ErrorException Undefined offset: 0

**Comment by itsgoingd** [comment]
Hey, the issue is actually not with the laravel-model-caching package itself, but with its dependency - https://github.com/fico7489/laravel-pivot - which is overriding base Eloquent events with a different format of the payload.

While we could do additional checking if the payload is in correct form, we can't reasonably support unpredictable Laravel core modifications done by other 3rd party packages.
