### ISSUE TITLE
Xdebug Profiler in WebUI not working

### ISSUE THREAD

**Issue by ragingdave** [itsgoingd/clockwork#277]
Something seems odd with the webUI as toggling the profiler just makes the UI toggle on it's own between Enable/Disable Profiler.

It will only ever settle on the profiler being disabled. As such I can't get profiler data for api based requests as they aren't accessible through the clockwork extension. The clockwork extension works flawlessly and is what prompted me to test this new (wonderful, thank you!) feature.

**Comment by itsgoingd** [comment]
Hey, that is a minor annoyance that I haven't been able to fix before release. Clockwork tries to be smart and not profile it's own metadata requests, but we can't simply disable the profiler for a single request, so you can see the entire profiler turning off and on again every time we fetch data.

There is a different problem with your api though. The Xdebug profiler is enabled by setting a particular cookie for the http request that should be profiled, that's what "enable profiler" in Clockwork does. Now when you are calling the api outside of a browser, the cookie is not set and profiler is not enabled.

To make this work, you need to modify the app making the requests to include a cookie with a value `XDEBUG_PROFILE=1` or the same parameter in your GET/POST data.

Alternativaly you can enable Xdebug profiler for *all* requests by setting `xdebug.profiler_enable=1` instead of `xdebug.profiler_enable_trigger` in your php.ini.

Though this can lead to a lot of extra unnecessary profiling data and running with profiler enabled slows down your app a lot.

**Comment by ragingdave** [comment]
Alright understood, and it makes sense. Thanks for explaining what's going on!
