### ISSUE TITLE
Feature: Explain database queries

### ISSUE THREAD

**Issue by sepehr** [itsgoingd/clockwork#281]
Would be wonderful if we had the chance to be able to see the explanation for each query in the database tab. 

![image](https://user-images.githubusercontent.com/23576/45149632-5907e580-b1ca-11e8-9e29-a0512f2b2ea1.png)

**Comment by itsgoingd** [comment]
Hey, this is definitively a good idea, but might have to wait for some further future release. Currently we can only pre-compute the explains, which would be unnecessary in most cases and slow. We might be able to do it the way xdebug profiler is implemented in 3.0, but I will need to play with this a bit.

**Comment by sepehr** [comment]
Thanks for considering this. 

TBH I'm not following what you're suggesting regarding xdebug profiler 3.0. The only feasible way I can see here, is to repeat the query prepended with `explain`. Just as [debugbar does it](https://github.com/barryvdh/laravel-debugbar/pull/210/files).

Yes, we might end up dispatching a lot of "extra" queries to the database which is, in fact, the price for the convenience we get in our development environment. Personally fine with me.

**Comment by itsgoingd** [comment]
Decided to skip this one for now.

Ideally this would work in a way where you would click on a button for a particular query to run explain for that query, which is beyond the scope of Clockwork atm.

The only way to implement this would be to run duplicate EXPLAIN queries for every executed query ever, which seems pretty wasteful and noisy.

That all for a just little bit of convenience, since you can easily copy the query from Clockwork to your favorite sql client and run the query there. I will add a single-click copy query button, should be pretty useful in general.

I still think this is a good idea though, might revisit for a later release if there is more demand for this.

**Comment by jaulz** [comment]
Just came about this as well and it would be super handy to see the `EXPLAIN` statement below the actual statement (instead of going the complicated way via copy/paste or the way you suggested via toggle). If we let users toggle the behaviour via a configuration option, everyone can decide if he wants to use it or not. In my special case I just would like to know if any of my queries does _not_ use any index.
