### ISSUE TITLE
No database queries or timeline

### ISSUE THREAD

**Issue by martbean** [itsgoingd/clockwork#283]
Hi,

I've set up Clockwork on a vanilla PHP site following the [installation instructions](https://underground.works/clockwork/installation/vanilla?#content) but I'm not seeing the Database tab and the Timeline is empty. I can add custom events to the Timeline but there's nothing by default - is that correct?

And am I doing something wrong regarding database queries?

<img width="1285" alt="screen shot 2018-09-13 at 12 10 00" src="https://user-images.githubusercontent.com/4639556/45485009-fb394780-b74d-11e8-9199-7f1f76b664d5.png">

Thanks,
Martin.

**Comment by itsgoingd** [comment]
Hey,

When using Clockwork with a framework like Laravel or Symfony we can automatically hook up into Eloquent or Doctrine, since the application structure is well-known.

In a vanilla php app, the database access can be implemented in many ways - using Eloquent, Doctrine or other library, using PDO, mysql/mysqlnd extensions directly, etc. The correct way to collect the queries will be specific to your implementation and can't be done automatically.

If you are using the PDO or mysql(nd) apis directly, I'd suggest wrapping them in your own database layer implementation, which you can then use for logging the executed queries to Clockwork.

If you'd like some examples on how would the implementation look like I'm happy to help.

**Comment by jecun** [comment]
Hi, I'm having the same issue. A little more info in the documentation could help us a lot

**Comment by itsgoingd** [comment]
Thanks for the feedback, I will try to write a blog post with some tips on using Clockwork in vanilla php apps over the weekend.

**Comment by martbean** [comment]
Awesome, thanks!

**Comment by itsgoingd** [comment]
Hey, just an update that I haven't forgotten about this. I've been busy and travelling without computer, but I hope to get this done this week.

I'd also like to improve the vanilla experience in a future Clockwork release, there is no reason for this to be so complicated it needs a blog post to explain. Thinking about adding a new facade-class, kinda like the `Clockwork\Clockwork`, but for the vanilla integration. With methods for registering db queries, resolving metadata, sending the right headers, etc.

**Comment by itsgoingd** [comment]
I've merged a new vanilla PHP integration to be included in Clockwork 3.1 - https://github.com/itsgoingd/clockwork/pull/291

Please take a look and give it a try, you can use `v3.x-dev` in your composer.json to get the new version.

You can find temporary documentation here - https://gist.github.com/itsgoingd/0223498a5043b7ca1643ef6e6ad7ee53

Let me know if you have any feedback or ideas on how to further improve the vanilla support.

**Comment by martbean** [comment]
Excellent, thanks for this! I'll check it out when I get a moment.
