### ISSUE TITLE
Clockwork creates folder with wrong ACL

### ISSUE THREAD

**Issue by devopsmica** [itsgoingd/clockwork#299]
Hi, 

I'm trying to get my head around a problem I'm experiencing. I want to be able to user a deployer user, without sudo privileges to delete older versions of my web app. The problem is that altgough deployer is part of the www-data group, he can't delete clockwork folder because clockwork use www-data user to create the folder and doesn't give access to other users in the group.

Where can I change this? 

Thanks!

**Comment by itsgoingd** [comment]
Hey, the directory is created with `0700` permissions, making it writable only for the owner user.

This is configurable, but the configuration is not exposed in the Laravel config file, so you would need to do this in code.

Instead of doing that, I'd suggest adding the directory to your git repo, making it being created on deploy under the correct user. All you need to commit is a `.gitignore` file in the `storage/clockwork` directory:

```
*.json
```
