### ISSUE TITLE
Lumen incorrect queries count

### ISSUE THREAD

**Issue by GijsGoudzwaard** [itsgoingd/clockwork#313]
For my application I need to call a route internally, since I need it to go through some middleware. To accomplish this I do something along the line of this:
```
app()->handle(
   //  modified request
);
```

When an internal route has been called clockwork will think it has been called multiple times when it's not. Clockwork says that 25 queries have been run, but in reality only 11 are being run. I've tested this with `DB::enableQueryLog()` and `DB::getQueryLog()`.

Clockwork also has a problem with `clock()->info(...)` when a route is called internally, it will log multiple instances even when a method is only called once. When I place an `echo` or `Log` (laravel facade) instead of `clock()->info(...)` it will show the correct amount of times that the method has been called.

I'm on lumen version 5.8.1, though this has been an issue on 5.7 and 5.6 too I believe.

**Comment by itsgoingd** [comment]
Hey,

the issue is Clockwork, like most PHP code, expects each request to start with a clean slate, so no data leaks from one request to another. This is not true in your case, since you are handling a "subrequest" with an already populated app container.

For example if you were to set a value in the container in your "main" request:

```php
// GET /
app()->instance('foo', 'bar');
app()->handle(new \Illuminate\Http\Request('/foo', 'GET'));
```

You will find it is defined even in your subrequest:

```php
// GET /foo
return app('foo'); // returns "bar"
```

To reuse existing application instance this way requires both your and all third-party code to be written without the assumption that each request starts with a clean slate.

As for Clockwork, I have some ideas how to improve the behavior, but it's unlikely we'll ever fully support this usage.

In the long run I'd suggest refactoring your controller and middleware code to the point where you can call a simple method or make a full HTTP request instead of doing this. While this is obviously not worth doing just for Clockwork, you might run into issues with other packages, your own code or Laravel itself.

**Comment by GijsGoudzwaard** [comment]
For my use case I can't really refactor this or make an additional HTTP request. However before calling the internal route I could reset the laravel service container. Which services do I need to forget before calling the internal route?

**Comment by itsgoingd** [comment]
Unfortunately I don't think that would help, you want to run your subrequest in a different container context and return to the previous state, not just reset the state.

You could try disabling Clockwork (`config([ 'clockwork.enable' => false ])`) before making the subrequest and re-enabling after, this might disable the part of Clockwork code that leads to the duplication and might even keep the collected data from the subrequest (I'm really not sure atm).
