### ISSUE TITLE
Please remove merged branches

### ISSUE THREAD

**Issue by mahagr** [itsgoingd/clockwork#326]
You can safely remove all merged branches, it would clean up the project a lot and speed up composer if using dev-master. :)

**Comment by itsgoingd** [comment]
Removed all stale branches, thanks for reminding me. 👍

**Comment by mahagr** [comment]
Thank you. I just started to integrate clockwork into Grav CMS and I may have some pull request coming in soon(ish). One is about using proper PHP doc blocks (type hints in IDEs aren't working without them), but there are also some other things that I'd like to improve.

**Comment by itsgoingd** [comment]
Looks cool, let me know if you need any help with the integration, I'm always down to talk.

I welcome any contributions, but it's always best to first make an issue describing the idea, since a lot of things that seem to be oversights, eg. the non-standard code-style, are actually a deliberate decisions and I'd hate to waste your time. Doc blocks is also something I would need to think through.
