### ISSUE TITLE
Clockwork Enhancement Ideas

### ISSUE THREAD

**Issue by rhukster** [itsgoingd/clockwork#327]
Apologies if this is not the correct place, but the Feature Ideas issue #321 was closed. 

We are incorporating Clockwork in Grav CMS as an option over the existing PHPDebugBar. We've already got it added and working in our 1.7 branch (https://github.com/getgrav/grav/tree/1.7), but we've run into a few issues and limitations. We're using the latest `dev-master` version and I know you are working on the `4.0` release so maybe some things could be taken into consideration for that release?

* Grav is flat file based, so references to database timings are not relevant.  Would be nice if the extension didn't display those timings if they were not set, or perhaps an option to remove them?

![Image 2019-06-05 at 10 38 59 AM](https://user-images.githubusercontent.com/1084697/58973845-2fdaac80-877e-11e9-9c9c-e106c237b3cf.png)

* An option to control the order of the Clockwork tabs would be a nice to have as we like to put the `Performance` tab first, before `Request`.

* The expandable tree view of data in the `Log` tab is great but would be awesome to have more options (like open all nodes, close all nodes, etc) as it's useful to output complex data in there, but a pain to dig in on every request.

* Possibility to have count badges on tabs?  This would be very useful to show at a glance the number of items in a custom tab.

* Profiler support is cool, but the Xdebug profiler is super slow compared to XHProf.  Support for XHProf for profiler would be a welcome addition. (https://github.com/tideways/php-xhprof-extension)

* Grav uses Twig rather than Laravel Blade, but I implemented the Twig Profiler into Views via a new `Timeline()`, however it doesn't actually show a timeline, just the data.  I think this is not fully finished as your site doesn't show one either?

![Image 2019-06-05 at 11 13 25 AM](https://user-images.githubusercontent.com/1084697/58975776-007a6e80-8783-11e9-8499-22d21f67291a.png)

* UserData field support for objects/arrays similar to the log tab?

We would also be willing to get our hands dirty and offer up some PRs on this when time permits, but wanted to put these things out there first to see if you are willing to consider them.  Cheers!

**Comment by itsgoingd** [comment]
Hey, this is definitively the right place, I've locked the "main" issue so discussions about different feature ideas won't get mixed up.

Not really familiar with Grav, looks interesting. Clockwork 4.0 is pretty much done at this point, should be released in a few days, so you can require a stable version soon. The client-side was entirely rewritten, you can find the new code at https://github.com/underground-works/clockwork-app.

**Database metrics** - will definitively remove the 0 values from the performance tab, not so sure about requests list, but I'll consider it. I'd also like to include an ability to add custom metrics to performance tab in the future.

**Tabs reordering** - sounds pretty good, won't make 4.0, but will consider for a future release. That being said, the request tab was actually removed in 4.0 and replaced by a request sidebar, which you can collapse if you are not interested in the data. So performance is indeed the new default tab. You can check out the 4.0 client-side code in the repo linked above.

**Log data** - collapsing/folding the whole tree seems like a good idea. Might add a modifier key, like ctrl, which will make the collapse/fold action affect the whole sub-tree. Seems pretty simple to do, I'll try to include this in 4.0.

**Tabs badges** - something I've tried to avoid so far, but it was requested a few times so I might reconsider. In 4.0 we have a new "performance log" in the now default performance tab, which you can use to log custom performance-related messages that you want to see right away. Also the number of error and warning messages logged is shown in the requests list.

**XHProf** - the profiler feature in Clockwork is currently tied to the callgrind-style profile file format that Xdebug uses. Unfortunately XHProf uses some custom format afaik, but a quick google search found this code for converting the XHProf format to the callgrind format that Xdebug/Clockwork uses - https://github.com/tlevi/xh2cg. This might be a pretty simple way to implement this feature.

**Views** - this is one of the more underdeveloped Clockwork features, since it's disabled by default and I've never used it much. I'm definitively not opposed to improvements here, I'm particularly interested in the Twig profiler integration, since I'm also using Twig all the time. The `Timeline` component is used here just as a data storage, it was never intended to be displayed as timeline.

For the time being you can add the rendered views to the performance tab timeline yourself. But the timeline feature is due for a bigger rework, since there are more things, like database queries, that would make sense to present in this way.

**User data** - didn't even know this wasn't supported! Will add in 4.0.

Thanks for the well-written features list. I'll try to add the simpler stuff (database metrics, log data, user data) in 4.0, then we can take a look at the bigger ones, I'm definitively open to PRs if you will be interested in working on some of those.

**Comment by rhukster** [comment]
Thanks for getting back to me with great detail :) I just installed the 4.0 client, so my comments below are in relation to that.

**Tabs reordering** - Performance tab being the main tab really solves the immediate question, but it does bring up another slight issue.  It seems the **Request** tab is a fixed width with no ability to drag to resize (as most panels do).  This makes the request data very hard to read:

![Screen Recording 2019-06-06 at 08 27 AM](https://user-images.githubusercontent.com/1084697/59040996-03359c00-8835-11e9-86d6-6eb72412cf7d.gif)

Also, purely cosmetic thing, but having the scrollbars match the dark theme would be lovely :)

**Tabs badges** - The badges in the requests lists for errors/warnings are great, but custom ones would be useful.  In our case, we have a deprecated tab where we list deprecated warnings regarding upcoming Grav or vendor libraries (Twig, Symfony, etc).  This is really useful for people to see what they need to address now to make sure things are compatible going forward.  Without a badge on the tab though, people are unlikely to check it to know they have deprecated issues they should fix).  If we could get a custom badge in the request list, that would serve also.

**XHProf** - The output is pretty basic, and you can get at it easily enough via PHP.  We are simply outputting it to the log for now:

![Image 2019-06-06 at 8 17 12 AM](https://user-images.githubusercontent.com/1084697/59040258-8a821000-8833-11e9-92e6-b7ce18325d43.png)

**Views** - The biggest problem I have with Twig profiler and the one that will be an issue for the existing timer, is that I don't actually have any way to get the start_time out of the profiler data. It's there in the profiler itself for each call, but I can't access it! Grrr,  only the elapsed time, and the percentage of the total time.  However, the data is nested to let me build a tree of calls. The initial rough code for this is here: https://github.com/getgrav/grav/blob/1.7/system/src/Grav/Common/Twig/TwigClockworkDataSource.php and here: https://github.com/getgrav/grav/blob/1.7/system/src/Grav/Common/Twig/TwigProfileProcessor.php

**Comment by rhukster** [comment]
Just realized that the main request tab issue is based on some long cookie names.  However, even in the session section where the vars are shorter, its still a bit limited to expand the data. Resize would still be most handy.

**Comment by itsgoingd** [comment]
Yeah, I'm aware of the problem with long keys. I want to try changing the layout so the value is on a next row below the key instead of on the same row. Might also experiment with resizing, but it's pretty hard to keep the design responsive.

Oops, as a Macbook user I've never seen the ugly scrollbars, definitively need to read up on styling scrollbars and fix it if possible.

Experimented a bit with the Twig profiler and timeline view in views tab. Still needs a lot of work, got a bunch of ideas, will try to get this one for 4.1.

<img width="1392" alt="Screenshot 2019-06-06 at 22 17 50" src="https://user-images.githubusercontent.com/821582/59064730-43376600-88ab-11e9-8a19-2e77ea356eae.png">

Code at https://github.com/itsgoingd/clockwork/tree/twig-profiler and https://github.com/underground-works/clockwork-app/tree/views-timeline.

**Comment by rhukster** [comment]
Oh, that Twig profiler view looks really nice!

For scrollbars, I can recommend https://github.com/Grsmto/simplebar, I use them on https://learn.getgrav.org

For the adjustable width maybe this? https://split.js.org/ it's simple and small

**Comment by rhukster** [comment]
I got your new stuff integrated with Grav now.  Any chance these can be merged into main development branches?

![Image 2019-06-07 at 2 07 25 PM](https://user-images.githubusercontent.com/1084697/59130792-a8cc3680-892d-11e9-90fd-aa3ac1db581c.png)

**Comment by mahagr** [comment]
Related to Grav, there are some repeated calls (same method multiple times) and right now to make them to show up in the timeline I need to give them random name to make them to show up multiple times. That is OK, but I was thinking if there was a change to add support to show all of them in a single line as it would give better indication of how much time was spent in doing similar actions? Right now if the list of calls is long, you cannot really get a summary as you need to keep on scrolling down.

**Comment by robclancy** [comment]
I finally decided to add issues for things that have annoyed me or I have wanted for over a year now. Some of them are in this issue.

The main one I'm going to repeat from above which we would benefit from a lot is the count on the tabs. Especially the database tab.

**Comment by itsgoingd** [comment]
Thanks.

As for the timeline component, some of the missing features I'd like to address in future (possibly in 4.1):

- parent-children relations between events (eg. logging user-creation event that has db query sub-events)
- some way of tagging of events of the same type (eg. tagging all db query events)
- showing various other time-based data as timeline (eg. db quries, events, rendered views)
- ability to specify color per event/tag (eg. all db queries are rendered red, framework events blue, etc.)
- simplified server-side api for adding events

**Comment by mahagr** [comment]
Related to tagging; we already have tagging on log messages, but there's missing filtering in it. :)

**Comment by rhukster** [comment]
@itsgoingd Any news on the Twig profiler feature branch getting merged into 4.x ?

**Comment by itsgoingd** [comment]
@rhukster Hey, the current release plan is:

- 4.1 in late December / early January
- 4.2 in spring 2020 (if there is enough stuff for release)
- 5.0 in summer / fall 2020

The 4.1 already looks like a pretty big release (mainly focused on debugging cli commands, tests and queue jobs), but I don't see why we couldn't merge this since the initial implementation is already done. I will also review other suggestions here again so they can make it into either 4.1 or 4.2.

**Comment by rhukster** [comment]
Great thanks, looking forward to it.  We've implemented Clockwork in Grav 1.7 (currently at RC2 status). We hope to release Grav 1.7 as stable in the next few weeks.

**Comment by itsgoingd** [comment]
@rhukster Just merged the twig profiler with some tweaks to master (https://github.com/itsgoingd/clockwork/pull/365).

There is also new support for profiling console commands, queue jobs and tests, all available in master. If any of those sound interesting for your project, you can check the closed PRs for more info - https://github.com/itsgoingd/clockwork/pulls?q=is%3Apr+is%3Aclosed (though most of those features are fairly Laravel-specific).

Let me know how this works for you!
