### ISSUE TITLE
RedisManager not working with lumen 5.8.*

### ISSUE THREAD

**Issue by plourded** [itsgoingd/clockwork#347]
Lumen RedisServiceProvider register redis like that:

```
$this->app->singleton('redis', function ($app) {
            $config = $app->make('config')->get('database.redis', []);

            return new RedisManager($app, Arr::pull($config, 'client', 'predis'), $config);
});
```

And vendor/itsgoingd/clockwork/Clockwork/Support/Laravel/ClockworkServiceProvider.php
access it like that:

```
$this->app[RedisManager::class]
```
Not the same name!

Work around, in bootstrap/app.php, after the register of Illuminate\Redis\RedisServiceProvider, I do this:

```
$app->singleton(\Illuminate\Redis\RedisManager::class, function ($app) {
    return $app["redis"];
});
```

**Comment by itsgoingd** [comment]
Both Lumen and Laravel register these class aliases, just the Lumen list 

https://github.com/laravel/lumen-framework/blob/5.8/src/Application.php#L935-L964

 is way less extensive then the Laravel one 

https://github.com/laravel/framework/blob/6.x/src/Illuminate/Foundation/Application.php#L1129-L1173

Might be worth opening an issue on the Lumen repo to see if they can include a complete aliases list.

I'm not even sure why do they register aliases this way instead of in the service providers themselves.

Btw. you can simplify your fix to:

```php
$app->alias('redis', \Illuminate\Redis\RedisManager::class);
```

**Comment by plourded** [comment]
thanks!
