### ISSUE TITLE
Compatibility with `monolog/monolog:^2.0`

### ISSUE THREAD

**Issue by mrtus** [itsgoingd/clockwork#366]
As you might know `monolog/monolog:^2.0` has been released a while ago and as a developer we want our projects to be up-to-date with those latest packages updates.

Sadly `itsgoingd/clockwork` loses compatibility when upgrade to `monolog/monolog:^2.0` because there is a missing `: void` type hint on `ClockworkHandler`.

Now, applying this return type would mean a major version bump of `itsgoingd/clockwork` since we would break compatibility with PHP 5.x. Is this something we can do? No longer support older PHP versions?

Since PHP 5.x has reached its end-of-life I would consider this an okay upgrade for this library.

What are your thoughts on this?

**Comment by itsgoingd** [comment]
Hey, I kinda forgot we ship a Monolog handler, since I never used it myself and it's not even documented, but I see no reason why we wouldn't support Monolog 2.x since we already have the handler.

I would definitively prefer to ship two handlers though, for both Monolog 1.x and 2.x. Since 2.x is a pretty fresh release and drops support for not only PHP 5.x, but also 7.1 and 7.2, I would expect 1.x to still be widely used for quite some time.

Ideally we would rename the existing handler to `ClockworkLegacyHandler` and replace with a 2.x one, but that would still be a breaking change and the next major release is scheduled for the fall at the earliest.

So the best solution seems to be adding a new `Support\Monolog2\Handler\ClockworkHandler` in Clockwork 4.1 for now and consider renaming at a later point.

**Comment by mrtus** [comment]
@itsgoingd Thank you for your answer! I guess our solution will be to write our own handler for Clockwork, which is fine too I guess 👍
