### ISSUE TITLE
Can't get stack trace to work

### ISSUE THREAD

**Issue by incentfit** [itsgoingd/clockwork#375]
I'm using clockwork 4.0.15 vanilla on my local php server, along with the chrome extension.  I am initializing clockwork with no custom configurations or environment variables.  I use the `addDatabaseQuery` functions, as well as `startEvent` and `endEvent` to track relavent events.  It is mostly working, I am getting information the Performance tab as well as the Database tab.  

However, I cannot get the stack traces to work anywhere.  I tried setting stack trace to true in the options going to `addDatabaseQuery` but the chrome extension just shows an empty expansion box.  To test if further, I tried putting in the following in my PHP `clock()->info("Trace this message!", [ 'trace' => true ]);` and I see the note come through into the extension but instead of a stack trace it just shows the following:
![image](https://user-images.githubusercontent.com/13243272/73428258-aed0b680-4306-11ea-8161-f5be1fb916f3.png)
I have xdebug and stepped into the info function and traced it through to see that it does indeed generate the trace array, but beyond that I'm not sure what's going wrong.
Am I doing something wrong here?

**Comment by itsgoingd** [comment]
Hey, this is indeed quite confusing.

Turns out we don't actually collect a trace when you call `addDatabaseQuery` and similar apis. You are expected to pass in the trace yourself ...and properly serialized, huh. This is how it can be done:

```php
use Clockwork\Helpers\{ Serializer, StackTrace };

$clockwork->addDatabaseQuery('SELECT * FROM users WHERE id = 1', [ 'id' => 1 ], 0.02, [
	'connection' => 'mysql',
	'model' => 'User',
	'trace' => (new Serializer)->trace(StackTrace::get())
]);
```

This is definitively something we can improve, but it shouldn't be that hard to implement assuming you are calling the `addDatabaseQuery` only once in some sort of database abstraction layer.

For log messages this should work out of the box though, even without passing `[ 'trace' => true ]`, since the logger is collecting it's own stack trace.

**Comment by incentfit** [comment]
Yeah, I'd expect the trace parameter in the addDatabaseQuery to be a boolean and it should pull that trace on it's own.  That being said, I get that it might be difficult to change this over since it may be a breaking change in many places.  I've gone ahead and implemented your suggestion and I can confirm it is working.  Thank you!

With regards to the log message, though, is that a confirmed bug?

**Comment by itsgoingd** [comment]
I did not find any issues with log messages.

Can you try out this example and see whether it works for you?

https://github.com/underground-works/clockwork-examples/tree/master/Integrations/Vanilla-PHP
