### ISSUE TITLE
Issue with custom Laravel mail transport

### ISSUE THREAD

**Issue by tminich** [itsgoingd/clockwork#390]
I'm running into a bit of a hiccup trying to use a custom mail transport with Clockwork in Laravel.
Disclaimer first, I'm really new to Laravel so there may be something in the framework itself I'm not aware of to get around this issue. Any pointers in that case would be highly appreciated.

The issue I'm running into is this. We use our own mailing service for which I wrote a custom mail transport driver. The code is proprietary, but I based it on https://github.com/themsaid/laravel-mail-preview, which shows the same problem in case you need a test case.
The base of the problem, as far as I could get to it, is that if the custom mail driver is set for the main mail configuration, the Laravel bootstrap process halts with an 'Unsupported mail transport' error because Clockwork (if mail debugging is active) accesses the mail service provider before the module that provides the transport driver has a chance to register it.

For now I've disabled Clockwork's mail support because the only other option I found is a rather ugly workaround which I'd rather avoid at all costs.

Is there any other option I have to make a mail transport driver module and Clockwork play together nicely? We're using Laravel 7.5 in case that matters.

**Comment by itsgoingd** [comment]
hey, i can confirm this will most likely be a clockwork bug.

the mail support was implemented way before custom mail transports (i think thats new in laravel 6/7?), and works only with the default swift-based transport (it's implemented as a swift mailer extension).

this means it is not supposed work with custom transports, but we should definitively detect when this is the case instead of crashing. a better general notifications support using higher level apis is on the todo list.

thanks for the detailed report. i'll try to fix this later today.

**Comment by itsgoingd** [comment]
tagged 4.1.1 with a fix.

the issue was simply clockwork being initialized too soon by mistake. custom mail transports still use the swift mailer abstraction, so there are no compatibility issues there.
