### ISSUE TITLE
Symfony console integration

### ISSUE THREAD

**Issue by staabm** [itsgoingd/clockwork#395]
As you know - we integrated this great tool with REDAXO CMS.
The cms also integrates with symfony/console to provide a admin-only console.

Instead of doing a redaxo-console<->clockwork-console integration, we should instead have a symfony-console based integration, which should be bundled in https://github.com/itsgoingd/clockwork/tree/f8821bac3720c687d5081013ba8d9a2597594592/Clockwork/Support/Symfony IMO

That way the integration could be re-used by other symfony-console based applications

Wdyt?

**Comment by itsgoingd** [comment]
here is a proof-of-concept code for symfony console support

https://gist.github.com/itsgoingd/bc7ae61d2272672a4de42dff7c37b518

would this be useful for your integration?

i'm still not sure what the api should exactly look like and how it fits into our symfony integration, since the current symfony integration does not collect any data, only acts like a symfony profiler frontend.

**Comment by staabm** [comment]
thx for your suggestion. we decided to integrate the console with our framework in a more REDAXO-way, so we will not need this anymore.

sorry that you already invested your time into it :-/

**Comment by itsgoingd** [comment]
no problem, might still be useful in the future, glad you could find a way that works for you.
