### ISSUE TITLE
warnings in filestorage

### ISSUE THREAD

**Issue by staabm** [itsgoingd/clockwork#399]
I see this warnings in the php log, like 
- `fclose() expects parameter 1 to be resource, bool given`
- `flock() expects parameter 1 to be resource, bool given`

see

![grafik](https://user-images.githubusercontent.com/120441/83348456-18041d00-a32d-11ea-854e-283b2694b303.png)

feels like the filesystem storage should either prevent this warnings or throw a proper exception, in case this is a relevant error idication

using version 4.1.4

**Comment by itsgoingd** [comment]
forgot to respond here, sorry

the error means we failed to open the lock file (for writing), the error handling is non-trivial here, as you suggest we could

- throw a proper exception, which is the "correct" thing to do, but in some environments, eg. in production, we don't want to fail the whole request just because we can't save profiling data
- fail silently, which would cause the request to not appear in the clockwork ui and possibly inconsistent state between the collected metadata and index file
- better up-front validation in constructor, currently we only check if `file_exists`, more correct approach would be to check if `is_writable`, which would solve one source of possible issues, but the file opening could still randomly fail

i think the best approach atm would be to improve the up-front validation and fail silently if we still can't open the file. maybe in future we could have a "production mode" setting to switch between more or less strict error handling.

will keep open for a while to see if we can figure out something better.

**Comment by staabm** [comment]
> better up-front validation in constructor, currently we only check if file_exists, more correct approach would be to check if is_writable, which would solve one source of possible issues, but the file opening could still randomly fail

Agree. Thx for the detailed investigation

**Comment by itsgoingd** [comment]
i've tagged clockwork 4.1.6 with improvements as described above
