### ISSUE TITLE
How to disable collection temporarily at runtime?

### ISSUE THREAD

**Issue by mortenscheel** [itsgoingd/clockwork#401]
I can't seem to find a way to disable Clockwork collection dynamically at runtime. Is possible to do so?

I'm looking for a feature similar to Laravel Telescope's `Telescope::stopRecording()` and `Telescope::startRecording()`.

**Comment by itsgoingd** [comment]
hey, unfortunately we don't have such user-friendly api atm, but it's still (kind of) possible by changing the clockwork settings at runtime - `config([ 'clockwork.enable' => false ])`

this will make clockwork to not save the collected data, but the data is still collected (so you won't avoid the performance overhead).

to completely disable clockwork you would need to do this in a service provider that is executed before clockwork's one.

**Comment by mortenscheel** [comment]
Thanks for the answer. I did try setting `clockwork.enable` to false, but it didn't help in this case (running out of memory during a bulk-import action).

Would you be interested in a pull-request adding this feature, assuming I could find a clean way to do it? At first glance I think I'd add a static `$recordingSuspended` property to the base `DataSource` class. Then each concrete DataSource should check this property before they record a query/job/event/whatever.

API wise, I'd personally prefer something like this:
```php
clock()->suspendRecording();
// Do stuff that won't be recorded...
clock()->resumeRecording();

// Or with a callback
clock()->withoutRecording(function() {
   // Do stuff that won't be recorded.
});
```

**Comment by itsgoingd** [comment]
if you have a specific memory-intensive endpoint, you can completely disable clockwork for that uri using the `filter_uris` setting (similar setting exists for console commands and queue jobs)

https://github.com/itsgoingd/clockwork/blob/master/Clockwork/Support/Laravel/config/clockwork.php#L268-L281

i'm definitively interested in including a better api like the one you describe. i'm afraid the implementation here is not very straight-forward, i would prefer a systematic approach instead of just adding a ton of "if statements" to every event listener.

putting this on the todo list for the next release (which is a major release, so bigger changes are not off the table).

i'm always open for contributions if you'd like to give this a go. might be worth discussing your approach here or on the discord first, so you don't sink hours into something that won't make it. thanks!

**Comment by mortenscheel** [comment]
Sure, that makes sense. I don't have a lot of spare time these days, so I'll probably not pursue this any further.

I haven't read the source code for https://github.com/laravel/telescope, but I would suggest taking a look at that for inspiration on how to implement this.
