### ISSUE TITLE
Storage improvement opportunities 

### ISSUE THREAD

**Issue by staabm** [itsgoingd/clockwork#405]
We use clockwork in a „debug“-addon for our redaxo cms for the whole userbase since the latest release. People love it <3.

As of now the most relevant problem thoses users experience are..
- profile storage take a lot of space.. up to 30mb for a single request.. could we imagine a different storage format which is still fast enough but doesnt use so much space? Maybe gzip/deflate the json files could work? Maybe a different format should be utilized?
- profile storage eviction: would it make sense to have some kind of default strategy to delete profiles when they are old enough/they take too much space/or similar?

If you need further information feel free to ask.

(German) upstream issue: https://github.com/redaxo/redaxo/issues/3805

**Comment by itsgoingd** [comment]
hey, i'm glad your users like it!

i feel you on the storage issues, the biggest challenge in Clockwork development is balancing the amount of collected data with performance overhead and storage requirements.

we already do support gzip compression in file storage since Clockwork 4.0. it's disabled by default, you can turn it on in the config.

https://github.com/itsgoingd/clockwork/blob/master/Clockwork/Support/Vanilla/config.php#L65

it shown some promising results, with 50 requests using 78M (80.67s), improving to 1.9M (82.95s) in a simple benchmark for the original PR (https://github.com/itsgoingd/clockwork/pull/320). i encourage you to do your own benchmarks though, i would be interested in your experience to see if we can enable this by default in future.

we also support time-based metadata expiration. we keep 1 week worth of data by default, you can tweak this interval in the config.

https://github.com/itsgoingd/clockwork/blob/master/Clockwork/Support/Vanilla/config.php#L72-L84

note that we don't do cleanup on every request to avoid the performance overhead, there is a roughly 1 in 100 chance that cleanup will be run.

we could definitively explore an option to hard-cap the available disk space, the challenge is to do it without much performance overhead (as IO operations can be slow).

btw the storage implementation is extensible, so you can always experiment with writing your own. we also ship an SQL storage which might be useful in some cases.

https://github.com/itsgoingd/clockwork/blob/master/Clockwork/Storage/StorageInterface.php
https://github.com/itsgoingd/clockwork/blob/master/Clockwork/Storage/SqlStorage.php

**Comment by staabm** [comment]
We will give it a try and report back.

Thx for the exhaustive answer <3

**Comment by staabm** [comment]
Sorry for not providing feedback to you. We had updated clockwork and a new release of our cms but no Feedback from the endusers.

I pinged them again and hope they will report back.

Sorry again and thank you for the fix!

**Comment by staabm** [comment]
got positve feedback, regarding reduced filesizes.

thank you!

**Comment by itsgoingd** [comment]
Thanks, will do some more benchmarking and possibly enable compression by default in the next release.
