### ISSUE TITLE
Error on storing in SqlStorage when upgrading version

### ISSUE THREAD

**Issue by lubatti** [itsgoingd/clockwork#419]
Hi there! 

I upgraded clockwork library from `v3.0.2` to `v4.1.7`  and when tried to store a Request in SqlStorage, the statement that PDO executes, returns false (because of a schema missmatching) without throwing any exception. That continues whitout errors nor warnings until it tries to recover the data from the database. Unsurprisingly it returns false because no data from request has been stored.

I believe that, besides exception catching, a boolean statement result comparission has to be made. Leading the function as it follows:

```
    protected function query($query, array $bindings = [], $firstTry = true)
    {
        try {
            if ($stmt = $this->pdo->prepare($query)) {
                $result = $stmt->execute($bindings);
                
                if (false !== $result) {
                    return $stmt;
                }
            }
        } catch (\PDOException $e) {
            $stmt = false;
        }

        // the query failed to execute, assume it's caused by missing or old schema, try to reinitialize database
        if (! $stmt && $firstTry) {
            $this->initialize();
            return $this->query($query, $bindings, false);
        }
    }
```

**Comment by itsgoingd** [comment]
Hey, thanks for the report. How are you instantiating the storage?

The PDO error behavior is configurable. When you pass a dsn to the constructor we don't set the proper error mode when creating the PDO instance, this is definitively an issue on our side. When you pass your own PDO instance we just assume it's in the exception error mode, this is arguably also an issue.

I guess handling both cases as you propose would be the best solution. Would you like to make a PR?

The implementation is not quite right tho, since `$stmt` would not be falsy in the second condition, I think we could do:

```php
if ($stmt = $this->pdo->prepare($query)) {
    if ($stmt->execute($bindings)) return $stmt;
    throw new \PDOException;
}
```
