### ISSUE TITLE
How to use the timeline() functionality in Slimphp

### ISSUE THREAD

**Issue by seanhamlin** [itsgoingd/clockwork#463]
Hi there,

I am integrating Clockwork into a mid sized Slimphp `4.7.1` app that I look after. I have added the [middleware](https://underground.works/clockwork/#docs-installation-slim), and have got the base functionality working with the chrome extension.

![image](https://user-images.githubusercontent.com/10605846/102197520-26f79900-3f26-11eb-9c05-672edd72c0b8.png)

I now want to add additional events to the timeline, to help better visualise the major areas where the app is spending its time. e.g. Guzzle requests to third party APIs, loading data from files etc.

Reading the [docs](https://underground.works/clockwork/#docs-timeline)

```
clock()->event("Loading user's latest tweets via Twitter API")->start();
clock()->event("Loading user's latest tweets via Twitter API")->end();
```

This simply yields 

```
Call to undefined function clock()
```

If I manually require the helpers file 

```
require_once '../vendor/itsgoingd/clockwork/Clockwork/Support/Vanilla/helpers.php';
```

This does not return the actual `clockwork` instance

```
Call to a member function event() on null
```

Anyone know how to get the `clockwork` instance from the middleware in Slimphp 4?

**Comment by itsgoingd** [comment]
Hey,

Looks like this is not documented, but you can pass your own pre-configured Clockwork instance instead of the metadata path to the middleware, like this:

```php
$app = AppFactory::create();
$app->add(new Clockwork\Support\Slim\ClockworkMiddleware($app, $clockwork));
```

Now to create a simple Clockwork instance we can take inspiration from how the middleware does it:

```php
$clockwork = new Clockwork\Clockwork();

$clockwork->storage(new Clockwork\Storage\FileStorage($storagePath));
$clockwork->authenticator(new Clockwork\Authentication\NullAuthenticator);
```

At this point you will have a reference to the Clockwork instance, which you can use to add timeline events, log messages, etc.:

```php
$clockwork->event("Loading user's latest tweets via Twitter API")->start();
$clockwork->error('Something is not right.');
```

It might also be a good idea to register this instance with a dependency-injection container if you use one or to create your own clock() helper.

**Comment by seanhamlin** [comment]
Thanks @itsgoingd, that makes sense, let me have a crack at getting this up and running.
