### ISSUE TITLE
On-demand mode not work with cookie

### ISSUE THREAD

**Issue by yemenifree** [itsgoingd/clockwork#469]
Hi,

Thanks for great work on this,

I saw an issue with on-demand mode with a cookie flag when I was reviewing the codebase of clockwork for Laravel.

The `ClockworkMiddleware` will not push to kernel because this [if statmenet](https://github.com/itsgoingd/clockwork/blob/1de3f9f9fc22217aa024f79ecbdf0fde418fc0a1/Clockwork/Support/Laravel/ClockworkServiceProvider.php#L27) will not be `true` at all.

The clockwork browser extension uses a cookie to pass the secret of On-demand mode and the cookies on Laravel are not available when the boot of service provider executes.

I think it better if you can relay in the header of the request

**Comment by itsgoingd** [comment]
Hey, thanks for the report, this should be fixed in Clockwork 5.0.7.

The real issue here was the Laravel's cookie encryption middleware, which removes values for all unencrypted cookies unless specified in the `$except` property.

In Clockwork we run two checks whether the request should be collected. One early in the service provider, this one worked ok, since it ran before the cookie middleware. Another one is done at the end of request processing, before the collected data is stored, this one had the cookie values removed, so it always failed.

This was fixed by caching the incoming data from the first check and reusing them in the second.
