### ISSUE TITLE
Database query trace popover is cut-off by split pane, z-index seems too low

### ISSUE THREAD

**Issue by JackWH** [itsgoingd/clockwork#487]
When clicking on the Database tab, clicking a call point, and viewing the trace — the popover gets cut-off behind the sidebar. Screenshot example below.

I tried tinkering in Dev Tools with some different z-indexes, but I couldn't seem to get anything to work. This is in Safari 14.

Thanks for an awesome package!

<img width="769" alt="Screenshot 2021-03-18 at 12 06 33" src="https://user-images.githubusercontent.com/627533/111623655-8e9dd880-87e2-11eb-8f24-e0c5832f921a.png">

**Comment by itsgoingd** [comment]
Hey, thanks for the report.

Just in case you are interested in what the real problem is — it's an overflow issue with the middle content section. For the popover to be able to render outside the section we would need to set `overflow: visible`, but we have to use `overflow: auto` instead, to make the middle section scrollable.

To work-around this issue we always try to render the whole popover inside the middle section. If it's positioned near the edge it should be aligned in a way so it does not overflow. I guess this part of the code broke at some point, will get this fixed for 5.1.

**Comment by itsgoingd** [comment]
Fixed in Clockwork 5.1.
