### ISSUE TITLE
FileStorage->next() doesn't work from the first record

### ISSUE THREAD

**Issue by ssnepenthe** [itsgoingd/clockwork#511]
Seems like this is probably related to #510.

FileStorage->next($id) fails to load anything when $id is the ID of the oldest/first metadata file available.

To reproduce create a fresh laravel install with clockwork, visit the site and refresh a couple of times.

Check the storage/clockwork directory, note the id of the first metadata file and visit __clockwork/{id}/next.

The result should be a list of metadata records starting from the second oldest record but instead we get an empty array.

<img width="278" alt="Screen Shot 2021-08-04 at 10 50 21 AM" src="https://user-images.githubusercontent.com/10903810/128230046-f7807f6c-1e5e-4ebe-a4ef-a4e795470aad.png">

<img width="559" alt="Screen Shot 2021-08-04 at 10 50 51 AM" src="https://user-images.githubusercontent.com/10903810/128230057-a28740dd-74d5-4eae-bcb3-11cab2c7a05d.png">

**Comment by itsgoingd** [comment]
Hey, thanks for the report!

This is indeed an issue with how we read entries from the index file.

When seeking forward in the index we use a method called [FileStorage::readNextIndex](https://github.com/itsgoingd/clockwork/blob/master/Clockwork/Storage/FileStorage.php#L244-L260), which literally reads the next line from the index. This is what we want at all times.. except when we are right at the start of the file there is no previous line, so the first line of the file always gets skipped.

Will probably leave this for the 6.0 release cycle, since the index handling code is pretty finicky and it's a pretty niche edge case.

**Comment by itsgoingd** [comment]
I ended up simplifying the index handling slightly (https://github.com/itsgoingd/clockwork/commit/c6a7b1fe3b9327912518325b0fc3feefaa382bea), which also fixes this issue. This change will be included in Clockwork 5.3.
