### ISSUE TITLE
reduplicate slash

### ISSUE THREAD

**Issue by pys1992** [itsgoingd/clockwork#574]
clockwork version: v5.1.5
laravel version: v5.8

hi, I am not sure it is a bug or not.
This is my sql. I am not sure the model name is right. 
I think it should be `'App\\Models\\Components\\Barebom'`. Only tow slash not four.
<img width="1371" alt="image" src="https://user-images.githubusercontent.com/44765369/164359501-0786d4e3-e15c-4340-855b-97738d7bc639.png">

**Comment by itsgoingd** [comment]
Hey, this was indeed broken in 5.1.1 where we switched from `preg_raplace` to `preg_replace_callback` in the bindings processing code, both of these functions handle back-slahes in the replacement in different way.

Should be fixed in master (https://github.com/itsgoingd/clockwork/commit/369ca2d87e52c99a3e477b78949ded164f19b9f3).
