### ISSUE TITLE
Laravel catch Server-to-server requests

### ISSUE THREAD

**Issue by joelharkes** [itsgoingd/clockwork#629]
Laravel introduced events to catch server-to-server calls made in the framework: https://laravel.com/docs/10.x/http-client#events

```php
protected $listen = [
    'Illuminate\Http\Client\Events\RequestSending' => [
        'App\Listeners\LogRequestSending',
    ],
    'Illuminate\Http\Client\Events\ResponseReceived' => [
        'App\Listeners\LogResponseReceived',
    ],
    'Illuminate\Http\Client\Events\ConnectionFailed' => [
        'App\Listeners\LogConnectionFailed',
    ],
];
```

These can be used to catch server-to-server calls and show them in the logging or in a separate tab:

for example i did some simple HTTP request logging:
```
  Event::listen(function (RequestSending $requestSending) {
            $headersText = collect($requestSending->request->headers())
                ->map(fn($values, $key) => $key . ": ". (is_array($values) ? implode(", ", $values) : $values) )
                ->join("\r\n");
            clock("{$requestSending->request->method()} {$requestSending->request->url()}\r\n{$headersText}\r\n\r\n{$requestSending->request->body()}");
        });
```

Can this be added to the default framework integration?

**Comment by FeBe95** [comment]
## Background:
Some additional info on this from my side: I first read your [article on dev.to](https://dev.to/joelharkes/inspecting-server-to-server-requests-in-laravel-with-clockwork-a-how-to-guide-38ek) @joelharkes while researching this exact feature. Later, I found this open issue and noticed that you are the author of both the article and this issue. 😅

## Modifications:
Next I implemented your suggested code and modified it a bit in order to show the HTTP requests in the timeline. I stripped the header & body info from my code as I didn't need them for my specific use case.
I kept the logging feature since the links in the timeline are not clickable.

Further I changed the event registration to be inside the global `EventServiceProvider.php` file. FYI: I didn't need to add the `ClockworkMiddleware::class` into the `Kernel.php` as it works just fine without it in my case.

You can find my modified implementation in this gist:
https://gist.github.com/FeBe95/e6fcfd704799b0c17a02bce6ecd451ec


## Clockwork:

Apart from that I also modified Clockworks' code by adding one extra line here:

https://github.com/itsgoingd/clockwork/blob/954d18ef6b0fa01190769341e09e981303a7c17c/Clockwork/Request/Timeline/Event.php#L94-L98

To turn it into this:
```PHP
public function toArray()
{
	return [
		'name'        => $this->name,
		'description' => $this->description,
		'start'       => $this->start,
```

With this change I am able to achieve a behavior similar to how SQL queries are displayed:
I can set a short `method + host/path` string in the `name` field to display in the timeline bar and the `full url` string in the `description` field to display in the popup:

![popup](https://user-images.githubusercontent.com/7470739/233592664-cf3eb53a-3b7e-4105-872c-0f1ee6589295.png)

## Additional thoughts:
I'd love to see a default framework integration! Maybe a new "HTTP" tab could be introduced, just like the "Log" and "Database" tab. A new color + icon combination in the timeline for the requests would also be a nice addition.

I am very much looking forward to seeing this feature getting integrated into clockwork directly!

**Comment by itsgoingd** [comment]
Hey, thanks for the suggestion. I will leave this for the next major release, since I want to do a more complete integration, with a new tab for the HTTP requests as suggested above.

**Comment by itsgoingd** [comment]
This has been implemented a while ago and will be releasing in Clockwork 5.3 (https://github.com/itsgoingd/clockwork/pull/693).

**Comment by joelharkes** [comment]
nice @itsgoingd !
