### ISSUE TITLE
Changed default behavior 

### ISSUE THREAD

**Issue by fedorovsergey** [itsgoingd/clockwork#686]
Hello! 
In previous commit #679 was changed default behavior of main config

The 'enable' key was enabled by default , now it's not. It is not obvious in this commit, may be this is a mistake?

**Comment by DominicDetta** [comment]
This is my mistake despite the issue has been resolved by @UlrichEckhardt. 
I set default to false because we want probably use clockwork in production but for a very brief moment and of course with authentication. I'm aware of the danger. I didnt want to remember to disable clockwork.. I know I'm a lazy person.
No problem if you want to revert this value to be true by default.

**Comment by fedorovsergey** [comment]
I suppose you right, it would be more clear when developer must enable the plugin explicitly in config or other way.
I just wanted to point out that previous behavior has changed, and may be instructions or setup guid or smth should reflect these changes
