### ISSUE TITLE
chrome extension stuck on waiting

### ISSUE THREAD

**Issue by s4muel** [itsgoingd/clockwork#717]
hi, i dont think this is an issue of clockwork itself, but some of you might give me a hint to prevent it from happening.

couple of weeks ago i noticed the clockwork extension (5.1.1) stopped working in my chrome. the requests are stuck in "waiting" state.
i dug a bit and i suppose it is something on the "chrome" side (not really a problem, i think they hardened some security policy for extensions or whatever). here is my setup - i use clockwork in my local project, that is using self-signed certificate. site works, of course there is sometimes the warning about connection is not secure and strikethrough https...you know. but the clockwork extension doesnt. when i inspect the extension, i see `(failed)net::ERR_CERT_AUTHORITY_INVALID` in the network tab

![image](https://github.com/user-attachments/assets/d3603464-971c-41d2-84e6-174659a7d52e)

seems like this guy had the same issue https://github.com/itsgoingd/clockwork/issues/714
and there is a brief discussion on laracasts forum about this: https://laracasts.com/discuss/channels/laravel/clockwork-doesnt-work-in-chrome-debug-tools-but-works-in-firefox

it might be a problem for more extensions (if it is true that chrome changed some security behaviour), tried to google around, but couldnt find a solution or workaround. only thing i've found is `chrome://flags/#allow-insecure-localhost` that looked promisinf, but my project(s) sit on `project.test` and not localhost, so the flag seems to be not applied

as i mention in the forum, i could make it work (i hope) if i just use "better" certificates and import the CA to my chrome etc... but since it is a docker environment, it is a bit of a pain.

just letting you know, if you could possibly catch the error and display some meaningful error message or something instead of the infinite "waiting", that would be cool. and if someone comes up with a hint to solve it easily, that would be much cooler:D

ps: the web version of clockwork works fine, i am using that instead.

**Comment by freestyledork** [comment]
This is affecting me as well, it's nice to have dev tools open on the same page vs switching to the clockwork route. Looking forward to any updates/suggestions to fix this.

**Comment by longkhan786** [comment]
same issue for me on brave

**Comment by longkhan786** [comment]
I didn't find any solutions, which is why I switched to Firefox.

**Comment by m-develops** [comment]
On both Firefox and Chrome I still have this issue.

I am running Laravel in a docker container on http://localhost:4200/api

I have set CLOCKWORK_ENABLE to true in my .env

The files are created in /storage/clockwork

And are for example:
-rw-r--r--    1 root     root          4539 Oct 19 14:01 1729346501-8725-1501213603.json

Anything that should be changed to make this work on Docker?

**Comment by m-develops** [comment]
I found out the issue.

It was caused because the API was only available on the `http://localhost:4200/api` routes and Clockwork tries to send requests to for example `http://localhost:4200/__clockwork/{id}`

I needed to overwrite the registerRoutes method in the Laravel ClockworkServiceProvider to include the /api part.
So for example from:
![image](https://github.com/user-attachments/assets/b5332c99-ea01-4b5a-a189-819f76c9646d)

To something like:
![image](https://github.com/user-attachments/assets/768fb27a-3cc3-4e13-bfbf-2f606010fd03)

Also the `X-Clockwork-Path` header was not properly set.
So I added a middleware with:
![image](https://github.com/user-attachments/assets/72de5a64-049a-4733-b761-ea55cc383abe)

**Comment by itsgoingd** [comment]
Clockwork should auto-detect the path, maybe there is something atypical in your setup.

**Comment by itsgoingd** [comment]
Clockwork 5.3 will include improved error messaging for network errors. Unfortunately we can't detect exactly what kind of network error happened (like SSL certificate validation). The "More info" link leads to - https://underground.works/clockwork/#faq-error-loading-metadata

<img width="1025" alt="Screenshot 2024-10-21 at 21 19 32" src="https://github.com/user-attachments/assets/357a23a6-252d-42c1-9ac0-d175b21eae28">

**Comment by thosky** [comment]
I have the same problem on Chrome and Brave. But it works on Firefox. It stopped working some month ago - probably because chromium has upgraded ssl security.
As I see it the problem is that self signed certificates are considered unsafe and are blocked when loading as a browser extension. Of some reason this is not the case with Firefox which accepts it after the browser has approved the certificate.
It's not a problem loading clockwork with fx /clockwork as a page - it's only the extension part not working.
It's wird that the exension cannot be loaded even though the unsafe certificate has been accepted in the browser.

**Comment by itsgoingd** [comment]
@thosky Unfortunately there is nothing we can do about this, it's a Chrome issue, you can +1 it here - https://issues.chromium.org/issues/40882068

**Comment by Ahmed-Aboud** [comment]
@itsgoingd 
for me its stuck on "waiting" too and when i check the chrome extension console log

UPDATE: seems issue was the route return 404 because i use sub-domain for api request api.my-site and my route for fetching the api data was like www.my-site/clockwork

also for sub requests for vanilla apps this is needed in sendHeaders

```
        $subrequestHeader = [];
        foreach ($this->clockwork->request()->subrequests as $subrequest) {
            $id = $subrequest['id'];
            $url = urlencode($subrequest['url']);
            $path = urlencode($subrequest['path']);

            $subrequestHeader[] = "{$id};{$url};{$path}";
        }

        if (!empty($subrequestHeader)) {
            $this->setHeader('X-Clockwork-Subrequest', implode(',', $subrequestHeader));
        }

```

<img width="1643" height="451" alt="Image" src="https://github.com/user-attachments/assets/0c07d310-df09-48dc-aacb-21e7fbcabfb3" />
